create table contacts (
    id bigint generated by default as identity,
    email varchar(255),
    name varchar(255),
    user_id bigint,
    uuid  varchar(255),
    primary key (id)
);

create table users_automation (
    id bigint generated by default as identity,
    passwd varchar(255),
    email varchar(255),
    username varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    designation varchar(255),
    location varchar(255),
    user_image blob,
    permissions varchar(255),
    uuid  varchar(255),
    primary key (id)
);

alter table contacts add constraint FK_contacts_users foreign key (user_id) references users_automation;
